[tool.poetry]
name = "PythonWorkshop"
version = "0.1.0"
description = ""
authors = ["Prodigious Python"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
jupyter-book = "^0.11.2"
ipython = "^7.26.0"
jupyterlab = "^3.1.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
black-nb = "^0.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
