[tool.poetry]
name = "ProdigiousPython"
version = "0.1.0"
description = ""
authors = ["Prodigious Python"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ipython = "^8.7.0"
jupyterlab = "^3.5.2"
pyppeteer = "^1.0.2"

[tool.poetry.group.dev.dependencies]
black = {extras = ["jupyter"], version = "^22.12.0"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
