[tool.poetry]
name = "ProdigiousPython"
version = "0.1.0"
description = ""
authors = ["Prodigious Python"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
ipython = "^8.7.0"
jupyterlab = "^3.5.1"
jupyter-book = "^0.13.1"
pyppeteer = "^1.0.2"

[tool.poetry.dev-dependencies]
pytest = "^7.2"
black = {extras = ["jupyter"], version = "^22.10"}
black-nb = "^0.7"
sphinx-sitemap = "^2.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
