name: deploy-book

# Only run this when the develop branch changes
on:
  push:
    branches:
    - develop

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Configure poetry environment
      shell: bash
      run: |
        python -m pip install poetry
        echo The Poetry version installed is `poetry --version`
        python -m poetry config virtualenvs.in-project true
    - name: Check for valid pyproject.toml
      shell: bash
      run: poetry check

    - name: Install dependencies
      shell: bash
      run: python -m poetry install

    # Build the book
    - name: Build the book
      run: |
        python -m poetry run jupyter-book build .

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
